export interface IPokemon {
    id: string,
    name: string,
    pokedexEntries: {
        red?: string,
        blue?: string,
        yellow?: string,
        gold?: string,
        silver?: string,
        crystal?: string,
        ruby?: string,
        sapphire?: string,
        fireRed?: string,
        leafGreen?: string,
        emerald?: string,
        diamond?: string,
        pearl?: string,
        platinum?: string,
        heartGold?: string,
        soulSilver?: string,
        black?: string,
        white?: string,
        black2?: string,
        white2?: string,
        x?: string,
        y?: string,
        omegaRuby?: string,
        alphaSapphire?: string,
        sun?: string,
        moon?: string,
        ultraSun?: string,
        ultraMoon?: string,
        letsGoPikachu?: string,
        letsGoEevee?: string,
        sword?: string,
        shield?: string,
    }
}
